---
abstract: 'Interface to search CPAN Testers.'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  Moose: 2.0006
  Moose::Util::TypeConstraints: 2.0006
  MooseX::Params::Validate: 0.16
  Readonly: 1.03
  Test::More: 0
  WWW::Mechanize: 1.60
  namespace::clean: 0.20
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Testers-Search
provides:
  CPAN::Testers::Search:
    file: lib/CPAN/Testers/Search.pm
    version: 0.02
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
